In [51]:
from random import random
import numpy as np
import math
from math import exp

def actF(x):
    act = math.tanh(x)
    return [act,1-act*act]

def cross_entropy_loss(output, target):
    return (output - target)

def preprocess(filename):
    file = open(filename,'r')
    dataset = [line.split() for line in file]
    train_data = [np.array([float(row[0]),float(row[1])]) for row in dataset]
    
    train_labels = np.zeros((len(train_data),2))
    labels = [int(row[2]) for row in dataset]
    
    for i in range(len(labels)):
            train_labels[i][labels[i]] = 1    
    
    return train_data, train_labels

def softmax_norm(output_vec):
    l = [exp(x) for x in output_vec]
    npl = np.array(l)
    mysum = npl.sum()
    Dr = np.array([mysum for i in range(0,len(output_vec))])
    return (npl/Dr)

class NeuralNetwork:
    def __init__(self, n_input, n_hidden, n_output):
        init_weights = [[random() for x in range(n_input+1)] for i in range(n_hidden)]
        init_weights = np.array(init_weights)
        self.hidden_layer = {'W':init_weights}
        init_weights = [[random() for x in range(n_hidden+1)] for i in range(n_output)]
        init_weights = np.array(init_weights)
        self.output_layer = {'W' : init_weights}
        self.layers = 2
        
    def forward_prop(self, input_vector):
        inputs = np.append(input_vector,1)
        w_mat = nn.hidden_layer['W']
        prod = np.matmul(w_mat.reshape(3,4).transpose(),inputs.reshape(3,1))
        act = []
        delta = []
        for i in prod:
            act.append(actF(i)[0])
            delta.append(actF(i)[1])
        nn.hidden_layer['delta'] = np.array(delta)
        new_inputs = act
        new_inputs = np.append(new_inputs,1)
        w_mat = nn.output_layer['W']
        prod = np.matmul(w_mat.reshape(5,2).transpose(),new_inputs.reshape(5,1))
        act = []
        delta = []
        for i in prod:
            act.append(actF(i)[0])
            delta.append(actF(i)[1])
        nn.output_layer['delta'] = np.array(delta)
        return act
    
    def backward_prop(self, loss):
        loss = loss.reshape(2,1)
        error_grad = [a*b for a,b in zip(loss,nn.output_layer['delta'])]
        learning_rate = 0.1
        error_grad = np.array(error_grad).reshape(2,1)
        nn.output_layer['W'] = nn.output_layer['W'] - learning_rate*error_grad
        
        error_grad1 = nn.hidden_layer['delta'].reshape(4,1) * error_grad.sum().transpose()
        nn.hidden_layer['W'] = nn.hidden_layer['W'] - learning_rate* error_grad1
      
    
    def train_network(self, train_data, train_labels):
        
        

    
    
x = np.array([1,2,3,4])
# print(x.sum())
dataset = [[1,2],[2,1]]
labels = [1,0]
np.append(x,5)

train_data, train_labels = preprocess('dataset.txt')

nn = NeuralNetwork(2,4,2)
# print(nn.hidden_layer['W'])
# print(nn.output_layer['W'])
# nn.forward_prop()
row_count = 0;
sum_error = 0;
for row in train_data:
    if row_count == 1: break
    error = []
    output = nn.forward_prop(row)
    output = softmax_norm(output)
    loss = cross_entropy_loss(train_labels[row_count], output)
    nn.backward_prop(loss)
    sum_error += sum([(train_labels[row_count] - output)**2 for i in range(len(output))])
    print("loss :", loss)
    

loss : [ 0.49701501 -0.49701501]
loss : [ 0.46399481 -0.46399481]
loss : [ 0.43852482 -0.43852482]
loss : [ 0.50031646 -0.50031646]
loss : [ 0.49826414 -0.49826414]
loss : [ 0.45607833 -0.45607833]
loss : [ 0.4815576 -0.4815576]
loss : [ 0.47022073 -0.47022073]
loss : [ 0.4995604 -0.4995604]
loss : [ 0.49804255 -0.49804255]
loss : [ 0.42812925 -0.42812925]
loss : [ 0.44437762 -0.44437762]
loss : [ 0.50036604 -0.50036604]
loss : [ 0.50006704 -0.50006704]
loss : [ 0.50108401 -0.50108401]
loss : [ 0.4505894 -0.4505894]
loss : [ 0.50036252 -0.50036252]
loss : [ 0.50096373 -0.50096373]
loss : [ 0.32226878 -0.32226878]
loss : [ 0.50133991 -0.50133991]
loss : [ 0.50126566 -0.50126566]
loss : [ 0.50045805 -0.50045805]
loss : [ 0.50070958 -0.50070958]
loss : [ 0.49527449 -0.49527449]
loss : [ 0.49445916 -0.49445916]
loss : [ 0.43425319 -0.43425319]
loss : [ 0.50138877 -0.50138877]
loss : [ 0.50145673 -0.50145673]
loss : [ 0.33153304 -0.33153304]
loss : [ 0.50177495 -0.50177495]
loss : [ 0.38488

loss : [ 0.50000036 -0.50000036]
loss : [ 0.69361429 -0.69361429]
loss : [ 0.50415334 -0.50415334]
loss : [ 0.50405879 -0.50405879]
loss : [ 0.7004831 -0.7004831]
loss : [ 0.72892043 -0.72892043]
loss : [ 0.84725476 -0.84725476]
loss : [ 0.62961371 -0.62961371]
loss : [ 0.50001065 -0.50001065]
loss : [ 0.50216037 -0.50216037]
loss : [ 0.66242783 -0.66242783]
loss : [ 0.59140244 -0.59140244]
loss : [ 0.50000005 -0.50000005]
loss : [ 0.50003495 -0.50003495]
loss : [ 0.87139009 -0.87139009]
loss : [ 0.50344715 -0.50344715]
loss : [ 0.87571934 -0.87571934]
loss : [ 0.59158703 -0.59158703]
loss : [ 0.51124901 -0.51124901]
loss : [ 0.50000259 -0.50000259]
loss : [ 0.5001017 -0.5001017]
loss : [ 0.50000585 -0.50000585]
loss : [ 0.50000114 -0.50000114]
loss : [ 0.80006499 -0.80006499]
loss : [ 0.79430451 -0.79430451]
loss : [ 0.76432037 -0.76432037]
loss : [ 0.87567788 -0.87567788]
loss : [ 0.5 -0.5]
loss : [ 0.50000025 -0.50000025]
loss : [ 0.50309576 -0.50309576]
loss : [ 0.50010025 -0.50010

loss : [ 0.88056689 -0.88056689]
loss : [ 0.88056472 -0.88056472]
loss : [ 0.86679978 -0.86679978]
loss : [ 0.88053442 -0.88053442]
loss : [ 0.87891949 -0.87891949]
loss : [ 0.5 -0.5]
loss : [ 0.88078016 -0.88078016]
loss : [ 0.5 -0.5]
loss : [ 0.88066101 -0.88066101]
loss : [ 0.5 -0.5]
loss : [ 0.5 -0.5]
loss : [ 0.50000843 -0.50000843]
loss : [ 0.5 -0.5]
loss : [ 0.50000165 -0.50000165]
loss : [ 0.88065171 -0.88065171]
loss : [ 0.88064306 -0.88064306]
loss : [ 0.5 -0.5]
loss : [ 0.88074668 -0.88074668]
loss : [ 0.87975243 -0.87975243]
loss : [ 0.88057084 -0.88057084]
loss : [ 0.50000042 -0.50000042]
loss : [ 0.50000039 -0.50000039]
loss : [ 0.5 -0.5]
loss : [ 0.5 -0.5]
loss : [ 0.50000148 -0.50000148]
loss : [ 0.50199641 -0.50199641]
loss : [ 0.86582932 -0.86582932]
loss : [ 0.88042579 -0.88042579]
loss : [ 0.61334702 -0.61334702]
loss : [ 0.5 -0.5]
loss : [ 0.87942596 -0.87942596]
loss : [ 0.88074793 -0.88074793]
loss : [ 0.5 -0.5]
loss : [ 0.5 -0.5]
loss : [ 0.5 -0.5]
loss : [ 0.88

loss : [ 0.88066551 -0.88066551]
loss : [ 0.5 -0.5]
loss : [ 0.5 -0.5]
loss : [ 0.88075829 -0.88075829]
loss : [ 0.88075458 -0.88075458]
loss : [ 0.50000004 -0.50000004]
loss : [ 0.88079695 -0.88079695]
loss : [ 0.88078243 -0.88078243]
loss : [ 0.68921855 -0.68921855]
loss : [ 0.88078935 -0.88078935]
loss : [ 0.5 -0.5]
loss : [ 0.88079639 -0.88079639]
loss : [ 0.5 -0.5]
loss : [ 0.49998589 -0.49998589]
loss : [ 0.88011585 -0.88011585]
loss : [ 0.88078553 -0.88078553]
loss : [ 0.87923041 -0.87923041]
loss : [ 0.88078757 -0.88078757]
loss : [ 0.5 -0.5]
loss : [ 0.88078662 -0.88078662]
loss : [ 0.5 -0.5]
loss : [ 0.50000008 -0.50000008]
loss : [ 0.88076201 -0.88076201]
loss : [ 0.50000056 -0.50000056]
loss : [ 0.8807894 -0.8807894]
loss : [ 0.5 -0.5]
loss : [ 0.88078659 -0.88078659]
loss : [ 0.5 -0.5]
loss : [ 0.88078719 -0.88078719]
loss : [ 0.5 -0.5]
loss : [ 0.8807755 -0.8807755]
loss : [ 0.88079532 -0.88079532]
loss : [ 0.85769635 -0.85769635]
loss : [ 0.88077884 -0.88077884]
loss : [

In [41]:
w = np.zeros([2,5])
x = np.random.rand(2,1)
n = 0.1
print(w)
print(0.1*x)
print(w-0.1*x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.09898757]
 [0.08782891]]
[[-0.09898757 -0.09898757 -0.09898757 -0.09898757 -0.09898757]
 [-0.08782891 -0.08782891 -0.08782891 -0.08782891 -0.08782891]]
